### ISSUE TITLE
net::ERR_INTERNET_DISCONNECTED

### ISSUE THREAD

**Issue by JosefJezek** [garstasio/ajax-form#38]
Could you improve event submitted for status net::ERR_INTERNET_DISCONNECTED?

**Comment by rnicholus** [comment]
I'm not sure I understand the request.  Please provide more detail.

**Comment by JosefJezek** [comment]
```
form.addEventListener('submitted', function(event) {
                if (event.detail.status > 299) {
                    alertify.error('Submission failed!  Please try again.')
                }
                else {
                    content.innerHTML = 'Thanks!  Your choices have been submitted!';
                }
```
Status is 0 for correct response from server, but also for error net::ERR_INTERNET_DISCONNECTED.

**Comment by rnicholus** [comment]
Status won't be zero unless there is a problem

**Comment by JosefJezek** [comment]
On Chrome 39 is status 0. :-(

**Comment by rnicholus** [comment]
Then the request has failed in some way
