### ISSUE TITLE
501 unsupported method post

### ISSUE THREAD

**Issue by zenorocha** [garstasio/ajax-form#45]
After updating to v1.5.0 I get this error in each form submission on Chrome Canary:

![screen shot 2015-01-16 at 5 29 20 pm](https://cloud.githubusercontent.com/assets/398893/5783812/4468f85e-9da5-11e4-8e56-8e85079b542a.png)

**Comment by rnicholus** [comment]
I didn't see any issues during my testing, and confirmed today that all looks well.  Can you include your markup and any associated JS so I can look closer?  If the issue in Canary-specific, perhaps it's an issue with that particular build of Canary.

**Comment by zenorocha** [comment]
Yeah, sure.

HTML: https://github.com/liferay-apps/sample-auth/blob/master/admin/index.html#L46-L52
JS: https://github.com/liferay-apps/sample-auth/blob/master/js/my-account.js#L42-L70

Please don't judge, it's just an experiment ;)

https://liferay-auth.firebaseapp.com

**Comment by rnicholus** [comment]
Did you intentionally leave off the `action` attribute?  That will submit the form to the endpoint represented by the current browser context.  Other than that, everything looks good client-side.

**Comment by zenorocha** [comment]
I did, I thought that wouldn't raise an error because it didn't in 1.4.0, I'll close this one for now and keep investigating ;)
