### ISSUE TITLE
Headers not submitted?

### ISSUE THREAD

**Issue by bruce** [garstasio/ajax-form#49]
It appears that since the removal of core-ajax, custom headers aren't being submitted any longer. Looking through `ajax-form.js`, I don't see the headers being handled. (Is it possible I'm just missing something?)

**Comment by rnicholus** [comment]
Nope, you are 100% correct.  Guess I should have unit tests for this, to ensure it doesn't happen again.  I'll shouldn't be too hard for me to push out a hotfix release and some tests that address this in the near future.  Pull requests welcome though.

**Comment by rnicholus** [comment]
Fixed in 1.5.1 (just released), with a unit test.
